import { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Upload, X, ShieldAlert, ShieldCheck, ImageIcon, Loader2 } from 'lucide-react';
import axios from 'axios';

export default function ImageAnalysis() {
    const [file, setFile] = useState(null);
    const [preview, setPreview] = useState(null);
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);
    const fileInputRef = useRef(null);

    const handleFileChange = (e) => {
        const selected = e.target.files[0];
        if (selected && selected.type.startsWith('image/')) {
            setFile(selected);
            setPreview(URL.createObjectURL(selected));
            setResult(null);
            setError(null);
        }
    };

    const handleDrop = (e) => {
        e.preventDefault();
        const selected = e.dataTransfer.files[0];
        if (selected && selected.type.startsWith('image/')) {
            setFile(selected);
            setPreview(URL.createObjectURL(selected));
            setResult(null);
            setError(null);
        }
    };

    const clearFile = () => {
        setFile(null);
        setPreview(null);
        setResult(null);
        setError(null);
        if (fileInputRef.current) fileInputRef.current.value = '';
    };

    const analyzeImage = async () => {
        if (!file) return;

        setLoading(true);
        setError(null);

        const formData = new FormData();
        formData.append('file', file);

        try {
            const response = await axios.post('http://127.0.0.1:8000/detect-image', formData, {
                headers: { 'Content-Type': 'multipart/form-data' }
            });
            setResult(response.data);
        } catch (err) {
            console.error(err);
            setError("Analysis failed. Ensure backend is running and models are loaded.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="w-full max-w-4xl mx-auto">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="glass-panel p-8"
                style={{ padding: '2rem' }}
            >
                <h2 style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: 0 }}>
                    <ImageIcon size={24} color="var(--color-primary)" />
                    AI Generated Image Detection
                </h2>

                <p style={{ opacity: 0.7, marginBottom: '2rem' }}>
                    Upload an image to check if it was generated by AI models (Midjourney, DALL-E, Stable Diffusion).
                    We use an ensemble of 3 state-of-the-art models for maximum accuracy.
                </p>

                {/* Upload Area */}
                {!preview ? (
                    <div
                        onClick={() => fileInputRef.current?.click()}
                        onDragOver={(e) => e.preventDefault()}
                        onDrop={handleDrop}
                        style={{
                            border: '2px dashed rgba(255,255,255,0.2)',
                            borderRadius: '12px',
                            padding: '3rem',
                            textAlign: 'center',
                            cursor: 'pointer',
                            transition: 'all 0.2s'
                        }}
                        className="hover:bg-white/5 hover:border-primary"
                    >
                        <input
                            type="file"
                            ref={fileInputRef}
                            onChange={handleFileChange}
                            accept="image/*"
                            style={{ display: 'none' }}
                        />
                        <Upload size={48} style={{ opacity: 0.5, marginBottom: '1rem' }} />
                        <p><strong>Click to upload</strong> or drag and drop</p>
                        <p style={{ fontSize: '0.8rem', opacity: 0.5 }}>JPG, PNG, WEBP supported</p>
                    </div>
                ) : (
                    <div style={{ display: 'flex', gap: '2rem', alignItems: 'flex-start', flexWrap: 'wrap' }}>
                        {/* Preview */}
                        <div style={{ position: 'relative', flexShrink: 0 }}>
                            <img
                                src={preview}
                                alt="Upload preview"
                                style={{ maxHeight: '300px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)' }}
                            />
                            <button
                                onClick={clearFile}
                                style={{
                                    position: 'absolute',
                                    top: '-10px',
                                    right: '-10px',
                                    background: 'var(--color-card)',
                                    borderRadius: '50%',
                                    padding: '5px',
                                    border: '1px solid rgba(255,255,255,0.2)'
                                }}
                            >
                                <X size={16} />
                            </button>
                        </div>

                        {/* Actions / Results */}
                        <div style={{ flex: 1, minWidth: '300px' }}>
                            {!result && !loading && (
                                <button
                                    onClick={analyzeImage}
                                    style={{
                                        width: '100%',
                                        padding: '1rem',
                                        background: 'var(--color-primary)',
                                        color: 'white',
                                        border: 'none',
                                        borderRadius: '8px',
                                        fontWeight: 'bold',
                                        fontSize: '1.1rem'
                                    }}
                                >
                                    Analyze Image
                                </button>
                            )}

                            {loading && (
                                <div style={{ textAlign: 'center', padding: '2rem' }}>
                                    <Loader2 size={32} className="animate-spin" style={{ margin: '0 auto 1rem' }} />
                                    <p>Analyzing with 3 AI Models...</p>
                                </div>
                            )}

                            {error && (
                                <div style={{ color: 'var(--color-danger)', background: 'rgba(239,68,68,0.1)', padding: '1rem', borderRadius: '8px' }}>
                                    {error}
                                </div>
                            )}

                            {result && (
                                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                                    {/* Verdict */}
                                    <div style={{
                                        padding: '1.5rem',
                                        borderRadius: '8px',
                                        background: result.aggregate_score > 50 ? 'rgba(239, 68, 68, 0.1)' : 'rgba(34, 197, 94, 0.1)',
                                        border: `1px solid ${result.aggregate_score > 50 ? 'var(--color-danger)' : 'var(--color-success)'}`,
                                        marginBottom: '1.5rem',
                                        textAlign: 'center'
                                    }}>
                                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', color: result.aggregate_score > 50 ? 'var(--color-danger)' : 'var(--color-success)' }}>
                                            {result.aggregate_score > 50 ? <ShieldAlert size={32} /> : <ShieldCheck size={32} />}
                                            <h2 style={{ margin: 0 }}>{result.verdict}</h2>
                                        </div>
                                        <p style={{ margin: '0.5rem 0 0', opacity: 0.8 }}>
                                            Aggregate AI Probability: <strong>{result.aggregate_score.toFixed(1)}%</strong>
                                        </p>
                                    </div>

                                    {/* Model Breakdown */}
                                    <h4 style={{ opacity: 0.7, marginBottom: '1rem' }}>Model Breakdown</h4>
                                    <div style={{ display: 'grid', gap: '10px' }}>
                                        {Object.values(result.details).map((model, idx) => (
                                            <div key={idx} style={{
                                                background: 'rgba(255,255,255,0.05)',
                                                padding: '1rem',
                                                borderRadius: '6px',
                                                display: 'flex',
                                                justifyContent: 'space-between',
                                                alignItems: 'center'
                                            }}>
                                                <span>{model.name}</span>
                                                <div style={{ textAlign: 'right' }}>
                                                    <div style={{
                                                        fontWeight: 'bold',
                                                        color: model.ai_probability > 0.5 ? 'var(--color-danger)' : 'var(--color-success)'
                                                    }}>
                                                        {model.prediction}
                                                    </div>
                                                    <span style={{ fontSize: '0.8rem', opacity: 0.5 }}>
                                                        {(model.ai_probability * 100).toFixed(1)}% AI
                                                    </span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </motion.div>
                            )}
                        </div>
                    </div>
                )}
            </motion.div>
        </div>
    );
}
